
var __cov_qGbkhZXzQfQfRylMFrYFQw = (Function('return this'))();
if (!__cov_qGbkhZXzQfQfRylMFrYFQw.__coverage__) { __cov_qGbkhZXzQfQfRylMFrYFQw.__coverage__ = {}; }
__cov_qGbkhZXzQfQfRylMFrYFQw = __cov_qGbkhZXzQfQfRylMFrYFQw.__coverage__;
if (!(__cov_qGbkhZXzQfQfRylMFrYFQw['/Users/xdf/prjs/macaca/macaca-istanbul/demo/sample.js'])) {
   __cov_qGbkhZXzQfQfRylMFrYFQw['/Users/xdf/prjs/macaca/macaca-istanbul/demo/sample.js'] = {"path":"/Users/xdf/prjs/macaca/macaca-istanbul/demo/sample.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{"1":[0,0]},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":3,"column":2}},"2":{"start":{"line":2,"column":2},"end":{"line":2,"column":34}},"3":{"start":{"line":4,"column":0},"end":{"line":8,"column":1}},"4":{"start":{"line":5,"column":2},"end":{"line":5,"column":17}},"5":{"start":{"line":7,"column":2},"end":{"line":7,"column":17}},"6":{"start":{"line":10,"column":0},"end":{"line":12,"column":3}},"7":{"start":{"line":11,"column":2},"end":{"line":11,"column":9}}},"branchMap":{"1":{"line":4,"type":"if","locations":[{"start":{"line":4,"column":0},"end":{"line":4,"column":0}},{"start":{"line":4,"column":0},"end":{"line":4,"column":0}}]}}};
}
__cov_qGbkhZXzQfQfRylMFrYFQw = __cov_qGbkhZXzQfQfRylMFrYFQw['/Users/xdf/prjs/macaca/macaca-istanbul/demo/sample.js'];
__cov_qGbkhZXzQfQfRylMFrYFQw.s['1']++;window._runtime('const exec = () => {\n    console.log(\'exec\', new Date());\n};');const exec=()=>{__cov_qGbkhZXzQfQfRylMFrYFQw.s['2']++;window._runtime('console.log(\'exec\', new Date());');console.log('exec',new Date());};__cov_qGbkhZXzQfQfRylMFrYFQw.s['3']++;window._runtime('if (true) {\n    console.log(1);\n} else {\n    console.log(2);\n}');if(true){__cov_qGbkhZXzQfQfRylMFrYFQw.b['1'][0]++;__cov_qGbkhZXzQfQfRylMFrYFQw.s['4']++;window._runtime('console.log(1);');console.log(1);}else{__cov_qGbkhZXzQfQfRylMFrYFQw.b['1'][1]++;__cov_qGbkhZXzQfQfRylMFrYFQw.s['5']++;window._runtime('console.log(2);');console.log(2);}__cov_qGbkhZXzQfQfRylMFrYFQw.s['6']++;window._runtime('document.querySelector(\'#test\').addEventListener(\'click\', () => {\n    exec();\n});');document.querySelector('#test').addEventListener('click',()=>{__cov_qGbkhZXzQfQfRylMFrYFQw.s['7']++;window._runtime('exec();');exec();});
